"""Add rewards tables

Revision ID: 91ecee59e0f1
Revises: 81af4e6e1e76
Create Date: 2026-05-28 20:14:02.933411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91ecee59e0f1'
down_revision: Union[str, None] = '81af4e6e1e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS user_badge_counts CASCADE")
    op.drop_index('idx_badges_badge', table_name='user_badges')
    op.drop_index('idx_badges_earned', table_name='user_badges')
    op.drop_index('idx_badges_rarity', table_name='user_badges')
    op.drop_index('idx_badges_user', table_name='user_badges')
    op.drop_table('user_badges')
    op.execute("DROP VIEW IF EXISTS weekly_leaderboard CASCADE")
    op.execute("DROP VIEW IF EXISTS user_rewards_summary CASCADE")
    op.drop_index('idx_user_rewards_coins', table_name='user_rewards')
    op.drop_index('idx_user_rewards_flagged', table_name='user_rewards')
    op.drop_index('idx_user_rewards_last_activity', table_name='user_rewards')
    op.drop_index('idx_user_rewards_level', table_name='user_rewards')
    op.drop_index('idx_user_rewards_points', table_name='user_rewards')
    op.drop_index('idx_user_rewards_referral_code', table_name='user_rewards')
    op.drop_index('idx_user_rewards_user_uid', table_name='user_rewards')
    op.drop_table('user_rewards')
    op.drop_index('idx_ad_ip', table_name='ad_rewards')
    op.drop_index('idx_ad_type', table_name='ad_rewards')
    op.drop_index('idx_ad_user', table_name='ad_rewards')
    op.drop_index('idx_ad_user_date', table_name='ad_rewards')
    op.drop_index('idx_ad_watched_at', table_name='ad_rewards')
    op.drop_table('ad_rewards')
    op.drop_index('idx_user_vouchers_code', table_name='user_vouchers')
    op.drop_index('idx_user_vouchers_expires', table_name='user_vouchers')
    op.drop_index('idx_user_vouchers_status', table_name='user_vouchers')
    op.drop_index('idx_user_vouchers_user', table_name='user_vouchers')
    op.drop_index('idx_user_vouchers_voucher', table_name='user_vouchers')
    op.drop_table('user_vouchers')
    op.execute("DROP VIEW IF EXISTS active_vouchers CASCADE")
    op.drop_index('idx_streak_logs_date', table_name='user_streak_logs')
    op.drop_index('idx_streak_logs_user', table_name='user_streak_logs')
    op.drop_table('user_streak_logs')
    op.drop_index('idx_suspicious_created', table_name='suspicious_activities')
    op.drop_index('idx_suspicious_ip', table_name='suspicious_activities')
    op.drop_index('idx_suspicious_resolved', table_name='suspicious_activities')
    op.drop_index('idx_suspicious_severity', table_name='suspicious_activities')
    op.drop_index('idx_suspicious_user', table_name='suspicious_activities')
    op.drop_table('suspicious_activities')
    op.drop_index('idx_challenge_progress_challenge', table_name='user_challenge_progress')
    op.drop_index('idx_challenge_progress_claimed', table_name='user_challenge_progress')
    op.drop_index('idx_challenge_progress_completed', table_name='user_challenge_progress')
    op.drop_index('idx_challenge_progress_user', table_name='user_challenge_progress')
    op.drop_table('user_challenge_progress')
    op.drop_index('idx_vouchers_active', table_name='vouchers')
    op.drop_index('idx_vouchers_cost', table_name='vouchers')
    op.drop_index('idx_vouchers_featured', table_name='vouchers')
    op.drop_index('idx_vouchers_type', table_name='vouchers')
    op.drop_index('idx_vouchers_uid', table_name='vouchers')
    op.drop_index('idx_vouchers_valid_dates', table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index('idx_challenges_active', table_name='daily_challenges')
    op.drop_index('idx_challenges_date', table_name='daily_challenges')
    op.drop_table('daily_challenges')
    op.drop_index('idx_referrals_created', table_name='referrals')
    op.drop_index('idx_referrals_referred', table_name='referrals')
    op.drop_index('idx_referrals_referrer', table_name='referrals')
    op.drop_index('idx_referrals_referrer_ip', table_name='referrals')
    op.drop_index('idx_referrals_status', table_name='referrals')
    op.drop_table('referrals')
    op.drop_index('idx_transactions_created', table_name='user_transactions')
    op.drop_index('idx_transactions_currency', table_name='user_transactions')
    op.drop_index('idx_transactions_ip', table_name='user_transactions')
    op.drop_index('idx_transactions_reference', table_name='user_transactions')
    op.drop_index('idx_transactions_type', table_name='user_transactions')
    op.drop_index('idx_transactions_user', table_name='user_transactions')
    op.drop_index('idx_transactions_user_date', table_name='user_transactions')
    op.drop_table('user_transactions')
    op.drop_index('idx_bingo_reward_claimed', table_name='bingo_cards')
    op.drop_index('idx_bingo_user_week', table_name='bingo_cards')
    op.drop_index('idx_bingo_week_start', table_name='bingo_cards')
    op.drop_table('bingo_cards')
    op.drop_table('referral_milestones')
    op.drop_index('idx_languages_display_order', table_name='languages')
    op.create_index(op.f('ix_languages_display_order'), 'languages', ['display_order'], unique=False)
    op.create_index(op.f('ix_languages_is_active'), 'languages', ['is_active'], unique=False)
    op.drop_index('idx_states_is_active', table_name='states')
    op.create_index(op.f('ix_states_is_active'), 'states', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_states_is_active'), table_name='states')
    op.create_index('idx_states_is_active', 'states', ['is_active'], unique=False)
    op.drop_index(op.f('ix_languages_is_active'), table_name='languages')
    op.drop_index(op.f('ix_languages_display_order'), table_name='languages')
    op.create_index('idx_languages_display_order', 'languages', ['display_order'], unique=False)
    op.create_table('referral_milestones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('milestone_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bonus_coins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bonus_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('badge_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='referral_milestones_pkey'),
    sa.UniqueConstraint('milestone_count', name='referral_milestones_milestone_count_key')
    )
    op.create_table('bingo_cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('week_start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('card_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('completed_cells', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('completed_lines', sa.TEXT(), server_default=sa.text("'[]'::text"), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reward_claimed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.user_uid'], name='bingo_cards_user_uid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='bingo_cards_pkey'),
    sa.UniqueConstraint('user_uid', 'week_start_date', name='bingo_cards_user_uid_week_start_date_key')
    )
    op.create_index('idx_bingo_week_start', 'bingo_cards', ['week_start_date'], unique=False)
    op.create_index('idx_bingo_user_week', 'bingo_cards', ['user_uid', 'week_start_date'], unique=False)
    op.create_index('idx_bingo_reward_claimed', 'bingo_cards', ['reward_claimed'], unique=False)
    op.create_table('user_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('currency_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance_before', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance_after', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.user_uid'], name='user_transactions_user_uid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_transactions_pkey')
    )
    op.create_index('idx_transactions_user_date', 'user_transactions', ['user_uid', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_transactions_user', 'user_transactions', ['user_uid'], unique=False)
    op.create_index('idx_transactions_type', 'user_transactions', ['transaction_type'], unique=False)
    op.create_index('idx_transactions_reference', 'user_transactions', ['reference_id'], unique=False)
    op.create_index('idx_transactions_ip', 'user_transactions', ['ip_address'], unique=False)
    op.create_index('idx_transactions_currency', 'user_transactions', ['currency_type'], unique=False)
    op.create_index('idx_transactions_created', 'user_transactions', [sa.text('created_at DESC')], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referrer_uid', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('referred_uid', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('signup_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('articles_read_10', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('week_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('referrer_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('referred_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referred_uid'], ['users.user_uid'], name='referrals_referred_uid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_uid'], ['users.user_uid'], name='referrals_referrer_uid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='referrals_pkey'),
    sa.UniqueConstraint('referred_uid', name='referrals_referred_uid_key')
    )
    op.create_index('idx_referrals_status', 'referrals', ['status'], unique=False)
    op.create_index('idx_referrals_referrer_ip', 'referrals', ['referrer_ip'], unique=False)
    op.create_index('idx_referrals_referrer', 'referrals', ['referrer_uid'], unique=False)
    op.create_index('idx_referrals_referred', 'referrals', ['referred_uid'], unique=False)
    op.create_index('idx_referrals_created', 'referrals', [sa.text('created_at DESC')], unique=False)
    op.create_table('daily_challenges',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('daily_challenges_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('challenge_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward_coins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='daily_challenges_pkey'),
    sa.UniqueConstraint('challenge_date', name='daily_challenges_challenge_date_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_challenges_date', 'daily_challenges', ['challenge_date'], unique=False)
    op.create_index('idx_challenges_active', 'daily_challenges', ['is_active'], unique=False)
    op.create_table('vouchers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vouchers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('voucher_uid', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('voucher_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('points_cost', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('coins_cost', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('discount_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('discount_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('valid_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('total_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('remaining_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('user_limit', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('sponsor_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('sponsor_logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('redemption_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_uid'], name='vouchers_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='vouchers_pkey'),
    sa.UniqueConstraint('voucher_uid', name='vouchers_voucher_uid_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_vouchers_valid_dates', 'vouchers', ['valid_from', 'valid_until'], unique=False)
    op.create_index('idx_vouchers_uid', 'vouchers', ['voucher_uid'], unique=False)
    op.create_index('idx_vouchers_type', 'vouchers', ['voucher_type'], unique=False)
    op.create_index('idx_vouchers_featured', 'vouchers', ['is_featured'], unique=False)
    op.create_index('idx_vouchers_cost', 'vouchers', ['points_cost', 'coins_cost'], unique=False)
    op.create_index('idx_vouchers_active', 'vouchers', ['is_active'], unique=False)
    op.create_table('user_challenge_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('claimed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['daily_challenges.id'], name='user_challenge_progress_challenge_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.user_uid'], name='user_challenge_progress_user_uid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_challenge_progress_pkey'),
    sa.UniqueConstraint('user_uid', 'challenge_id', name='user_challenge_progress_user_uid_challenge_id_key')
    )
    op.create_index('idx_challenge_progress_user', 'user_challenge_progress', ['user_uid'], unique=False)
    op.create_index('idx_challenge_progress_completed', 'user_challenge_progress', ['completed'], unique=False)
    op.create_index('idx_challenge_progress_claimed', 'user_challenge_progress', ['claimed'], unique=False)
    op.create_index('idx_challenge_progress_challenge', 'user_challenge_progress', ['challenge_id'], unique=False)
    op.create_table('suspicious_activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.user_uid'], name='suspicious_activities_user_uid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='suspicious_activities_pkey')
    )
    op.create_index('idx_suspicious_user', 'suspicious_activities', ['user_uid'], unique=False)
    op.create_index('idx_suspicious_severity', 'suspicious_activities', ['severity'], unique=False)
    op.create_index('idx_suspicious_resolved', 'suspicious_activities', ['resolved'], unique=False)
    op.create_index('idx_suspicious_ip', 'suspicious_activities', ['ip_address'], unique=False)
    op.create_index('idx_suspicious_created', 'suspicious_activities', [sa.text('created_at DESC')], unique=False)
    op.create_table('user_streak_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('activity_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('points_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('streak_broken', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.user_uid'], name='user_streak_logs_user_uid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_streak_logs_pkey'),
    sa.UniqueConstraint('user_uid', 'activity_date', name='user_streak_logs_user_uid_activity_date_key')
    )
    op.create_index('idx_streak_logs_user', 'user_streak_logs', ['user_uid'], unique=False)
    op.create_index('idx_streak_logs_date', 'user_streak_logs', [sa.text('activity_date DESC')], unique=False)
    op.create_table('user_vouchers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('voucher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('voucher_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('redeemed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.user_uid'], name='user_vouchers_user_uid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], name='user_vouchers_voucher_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_vouchers_pkey'),
    sa.UniqueConstraint('voucher_code', name='user_vouchers_voucher_code_key')
    )
    op.create_index('idx_user_vouchers_voucher', 'user_vouchers', ['voucher_id'], unique=False)
    op.create_index('idx_user_vouchers_user', 'user_vouchers', ['user_uid'], unique=False)
    op.create_index('idx_user_vouchers_status', 'user_vouchers', ['status'], unique=False)
    op.create_index('idx_user_vouchers_expires', 'user_vouchers', ['expires_at'], unique=False)
    op.create_index('idx_user_vouchers_code', 'user_vouchers', ['voucher_code'], unique=False)
    op.create_table('ad_rewards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('ad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ad_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('coins_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('watched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.user_uid'], name='ad_rewards_user_uid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ad_rewards_pkey')
    )
    op.create_index('idx_ad_watched_at', 'ad_rewards', ['watched_at'], unique=False)
    op.create_index('idx_ad_user_date', 'ad_rewards', ['user_uid', sa.text('watched_at DESC')], unique=False)
    op.create_index('idx_ad_user', 'ad_rewards', ['user_uid'], unique=False)
    op.create_index('idx_ad_type', 'ad_rewards', ['ad_type'], unique=False)
    op.create_index('idx_ad_ip', 'ad_rewards', ['ip_address'], unique=False)
    op.create_table('user_rewards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_points_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_points_spent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('coins', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_coins_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_coins_spent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('level_progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('current_streak', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('longest_streak', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_activity_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('referral_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('referral_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('referral_coins_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_ads_watched', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('coins_from_ads', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_flagged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('flag_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('flagged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_premium', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('premium_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('coins >= 0', name='check_coins_non_negative'),
    sa.CheckConstraint('current_streak >= 0 AND longest_streak >= 0', name='check_streak_non_negative'),
    sa.CheckConstraint('level >= 1 AND level <= 100', name='check_level_range'),
    sa.CheckConstraint('points >= 0', name='check_points_non_negative'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.user_uid'], name='user_rewards_user_uid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_rewards_pkey'),
    sa.UniqueConstraint('referral_code', name='user_rewards_referral_code_key'),
    sa.UniqueConstraint('user_uid', name='user_rewards_user_uid_key')
    )
    op.create_index('idx_user_rewards_user_uid', 'user_rewards', ['user_uid'], unique=False)
    op.create_index('idx_user_rewards_referral_code', 'user_rewards', ['referral_code'], unique=False)
    op.create_index('idx_user_rewards_points', 'user_rewards', [sa.text('points DESC')], unique=False)
    op.create_index('idx_user_rewards_level', 'user_rewards', ['level'], unique=False)
    op.create_index('idx_user_rewards_last_activity', 'user_rewards', ['last_activity_date'], unique=False)
    op.create_index('idx_user_rewards_flagged', 'user_rewards', ['is_flagged'], unique=False)
    op.create_index('idx_user_rewards_coins', 'user_rewards', [sa.text('coins DESC')], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('badge_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('badge_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('badge_icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('badge_color', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('badge_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rarity', sa.VARCHAR(length=20), server_default=sa.text("'common'::character varying"), autoincrement=False, nullable=True),
    sa.Column('points_bonus', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('earned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.user_uid'], name='user_badges_user_uid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_badges_pkey'),
    sa.UniqueConstraint('user_uid', 'badge_id', name='user_badges_user_uid_badge_id_key')
    )
    op.create_index('idx_badges_user', 'user_badges', ['user_uid'], unique=False)
    op.create_index('idx_badges_rarity', 'user_badges', ['rarity'], unique=False)
    op.create_index('idx_badges_earned', 'user_badges', [sa.text('earned_at DESC')], unique=False)
    op.create_index('idx_badges_badge', 'user_badges', ['badge_id'], unique=False)
    # ### end Alembic commands ###
