"""update_menu_items_add_fields

Revision ID: d8b17fad2a2f
Revises: ae38ef860167
Create Date: 2026-04-21 15:39:09.261860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b17fad2a2f'
down_revision: Union[str, None] = 'ae38ef860167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('item_type', sa.String(length=20), nullable=True))
    op.add_column('menu_items', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('menu_items', sa.Column('placement', sa.String(length=20), nullable=True))
    op.add_column('menu_items', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('menu_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('menu_items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_menu_items_display_order', 'menu_items', ['display_order'], unique=False)
    op.create_index('idx_menu_items_is_active', 'menu_items', ['is_active'], unique=False)
    op.create_index('idx_menu_items_placement', 'menu_items', ['placement'], unique=False)
    op.create_index(op.f('ix_menu_items_display_order'), 'menu_items', ['display_order'], unique=False)
    op.drop_column('menu_items', 'type')
    op.drop_column('menu_items', 'order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('menu_items', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_menu_items_display_order'), table_name='menu_items')
    op.drop_index('idx_menu_items_placement', table_name='menu_items')
    op.drop_index('idx_menu_items_is_active', table_name='menu_items')
    op.drop_index('idx_menu_items_display_order', table_name='menu_items')
    op.drop_column('menu_items', 'updated_at')
    op.drop_column('menu_items', 'created_at')
    op.drop_column('menu_items', 'color')
    op.drop_column('menu_items', 'placement')
    op.drop_column('menu_items', 'display_order')
    op.drop_column('menu_items', 'item_type')
    # ### end Alembic commands ###
